### ISSUE TITLE
Mongo DB connection string in each getConnection call

### ISSUE THREAD

**Issue by glock18** [toymachiner62/mongo-factory#1]
Hey,

I was wondering why each getConnection() call requires connection string. I believe it's very inconvenient to pass it every time I need the connection, but what makes me doubt a bit is that I saw exactly same approach for postgresql connection pool, for which back then I chose to write a simple wrapper holding connection string, and allowing me to call getConnection() without parameters.

I acknowledge, that probably having an ability to use different databases might be a concern here, but even if it was used often, it doesn't seem an issue to add default connection setting (to be used by argumentless version of getConnection() )

Looking forward your thoughts on this matter.
Best wishes,
Vasiliy

**Comment by toymachiner62** [comment]
You need the connection string every time because all this library does is manages a pool. So when you call `mongoFactory.getConnection(connectionString)` all it does internally is says "hey is there already a connection for this string?" if so it returns it, if not, it creates a connection via the passed in string and then returns that connection.

Here's some of the magic: https://github.com/toymachiner62/mongo-factory/blob/master/index.js#L34-L41

You can write a wrapper method in your project as you described or what I do in my projects is use [node-config](https://github.com/lorenwest/node-config). 

Then I can do something like this all over my code and still only have 1 reference to my connection string:

default.json

``` json
{
  "mongoConnectionString": "mongo//blah"
}
```

file1.js

``` js
var config = require('config');
var mongoFactory = require('mongo-factory');

mongoFactory.getConnection(config.get('mongoConnectionString'))...
```

**Comment by glock18** [comment]
Thank you for the detailed reply, Tom.
